const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export function createPublicationPages(stories, projects, editorial) {
  const header = `<header class="site-header"><a class="site-brand" href="/">∞ &nbsp;Infinity Enterprises</a><div class="site-actions"><a class="site-link" href="/issues">The issue</a><button class="site-music" id="music-toggle" type="button" aria-pressed="false">Sound on</button><details class="toc"><summary>Contents</summary><nav class="toc-panel" aria-label="Site contents"><span class="toc-label">The publication</span><a href="/">Home</a></nav></details></div></header>`;
  const shell = (title, subtitle, body, eyebrow='Infinity Enterprises / The publication') => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#102435"><meta name="description" content="${esc(subtitle)}"><title>${esc(title)} · Infinity Enterprises</title><style>/* SHARED_CSS */</style><style>/* PUBLICATION_CSS */</style></head><body class="hub-page">${header}<main id="main"><section class="hub-hero"><span class="eyebrow">${esc(eyebrow)}</span><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></section><div class="hub-wrap">${body}</div></main><footer class="site-footer"><span>Infinity Enterprises · September 2026</span><div class="publication-links"><a href="/issues">Issues</a><a href="/contact">Contact</a><a href="/privacy">Privacy</a></div></footer><script>/* MUSIC_SCRIPT */</script><script>/* PUBLICATION_SCRIPT */</script><script>/* DISPATCH_SCRIPT */</script></body></html>`;
  const card = (href, image, label, title, copy) => `<a class="hub-card" href="${href}"><img src="${image}" alt="" loading="lazy"><div><span>${label}</span><h3>${title}</h3><p>${copy}</p><strong>Explore ↗</strong></div></a>`;
  const section = (heading, content) => `<section class="hub-section"><h2>${heading}</h2>${content}</section>`;
  const departments = (items) => `<nav class="dept-index" aria-label="Department index">${items.map(([name],i)=>`<a href="#department-${i+1}">${esc(name)}</a>`).join('')}</nav><div class="hub-departments">${items.map(([name,copy,href,label],i)=>`<article class="hub-department" id="department-${i+1}"><small>${String(i+1).padStart(2,'0')} / Department</small><h3>${esc(name)}</h3><p>${esc(copy)}</p><a href="${href}">${esc(label)} ↗</a></article>`).join('')}</div>`;
  const motorDepartments = [['Reviews','The feel and form of a machine, with reported road tests as this desk develops.','/motor','View the visual edition'],['Industry News','New releases, design shifts, and the people shaping mobility.','/daily-desk','Visit the news desk'],['Concept Garage','Future forms explored through sketches and clearly labeled concepts.','/motor','Enter the gallery'],['Motorsports','The choreography, engineering, and culture of competition.','/motor','Explore MOTOR'],['Buyer’s Guide','Careful comparison and ownership questions for a future buying desk.','/contact','Suggest a question'],['Custom & Tuning','Personal expression in the garage, from craft to performance.','/motor','Explore MOTOR']];
  const foodDepartments = [['Recipes','A growing table of repeatable dishes and the decisions behind them.','/contact','Suggest a dish'],['Chef Spotlight','The people, craft, and memory behind a plate.','/contact','Nominate a chef'],['Food Science','How heat, texture, fermentation, and chemistry change what we taste.','/inquiry','Explore the method'],['Drinks & Mixology','Rituals, ingredients, and ideas for a considered glass.','/contact','Send a note'],['Restaurant Radar','Places worth understanding, with firsthand visits labeled when published.','/contact','Suggest a place'],['Nutrition Notes','Evidence and context for claims about food and health.','/about/standards','Read our standard']];
  const practiceDepartments = [['Training Programs','Structure, consistency, and progress without the noise.','/form','Begin with FORM'],['Mindfulness','The art of paying attention while still and in motion.','/form','View the sequence'],['Recovery & Rehab','Rest and return, with qualified sources for clinical claims.','/about/standards','Read our standard'],['Yoga & Breathwork','A slower study of posture, breath, and presence.','/form','Explore the poses'],['Supplements','Claims assessed against evidence before recommendation.','/inquiry','Explore the journal'],['Performance Science','What measurement can reveal, and where it still falls short.','/learning','Follow a learning path']];
  const musicDepartments = [['Artist Profiles','The makers and influences behind the sound.','/contact','Suggest an artist'],['Album Reviews','Listening notes with context, attribution, and room for surprise.','/ether','Enter the listening room'],['Production & Gear','How texture, rhythm, and space get built.','/tech-lounge','Explore the tools'],['Charts & Trends','A future view of public charts, with source and date beside each figure.','/contact','Suggest a source'],['Live Shows','Performances and streams linked through their authorized publishers.','/contact','Suggest a show'],['Underground Spotlight','Find the voices that have not yet reached the front page.','/ether','Start listening']];
  const journalDepartments = [['Research Papers','Original and external papers with methods and status named clearly.','/journal','Read working notes'],['Case Studies','A question followed through a specific record.','/development/atlas','Inspect Atlas'],['Policy Analysis','The institutions and rules that shape public choices.','/enigmas','Read analysis'],['Peer Commentary','A space for attributed critique and informed reply.','/contact','Contribute a note'],['Data & Methods','The sources, assumptions, and limits behind a claim.','/about/standards','Read the standard'],['Abstracts','Concise entry points before the deeper work.','/journal','Open the journal']];
  const techDepartments = [['Gadgets','Objects worth examining for design and utility.','/tech-lounge','Enter the lounge'],['AI & Robotics','How intelligent systems meet the material world.','/development','See the prototypes'],['Software & Apps','Tools, interfaces, and the choices behind them.','/development/atlas','Inspect the ledger'],['Cybersecurity','Security questions grounded in evidence and responsible practice.','/inquiry','Explore the journal'],['Future Tech','New possibilities with their development stage plainly marked.','/development','See what is in development'],['Developer Corner','Methods and paths for the people building the next thing.','/learning','Explore learning paths']];
  const deskDepartments = [['Breaking News','A small, source linked feed of changing technology signals.','/daily-desk','See outside signals'],['World','Questions and developments beyond one border.','/enigmas','Read the essays'],['U.S.','American institutions, choices, and consequences.','/enigmas','Read the essays'],['Business','How products, markets, and organizations are changing.','/development','See the studio'],['Science','Evidence, uncertainty, and the stories behind discovery.','/journal','Explore research'],['Culture','The ideas and art that give a moment its texture.','/culture','Explore culture']];
  const opinionDepartments = [['Opinion Columns','A position, its reasons, and what could change it.','/blog#stage-labels','Read a note'],['Thought Experiments','Follow an idea past its comfortable first answer.','/enigmas','Read the essays'],['Social Commentary','Institutions and everyday life viewed with care.','/enigmas','Visit the reading room'],['Philosophical Essays','The long questions beneath the daily argument.','/enigmas','Explore essays'],['Personal Reflections','A voice and a point of view, labeled as such.','/about','Meet the Enterprise'],['Weekly Riddle / Enigma','A question for readers, beginning when the editorial rhythm is ready.','/subscribe','Follow the issue']];
  const first = stories[0];
  const issueCards = [
    card('/enigmas/' + first.slug, first.image, 'Cover story / Original analysis', esc(first.title), esc(first.dek)),
    card('/ether', '/media/ether-1.jpg', 'Culture / Listening room', 'The Ether Room', 'Four worlds for one cosmic funk journey.'),
    card('/motor', '/media/motor-1.jpg', 'MOTOR / Visual edition', 'Objects of motion', 'Supercars, classics, and the art of the machine.'),
    card('/food', '/media/food.jpg', 'Food / New department', 'The table as a world', 'Taste, craft, science, and the stories served between them.'),
    card('/music', '/media/ether-1.jpg', 'Music / Listening room', 'After the last light', 'An entrance to cosmic funk and the people behind the sound.'),
    card('/form', '/media/form-1.jpg', 'The Practice / Visual meditation', 'FORM', 'Seven portraits of stillness, movement, and attention.'),
    card('/journal', '/media/research.jpg', 'Inquiry / Working notes', 'Research Journal', 'Questions, methods, evidence, and limits.'),
    card('/development', '/media/development.jpg', 'The Enterprise / AI studio', 'In Development', 'The systems and ideas taking shape.'),
  ];
  const pages = {
    '/issues': shell('The issues.', 'A living archive of the magazine. Start with September 2026 and follow the work as the next edition takes shape.', section('Volume 01 / September 2026', `<p class="hub-meta">Published issue · Original illustration and analysis</p><div class="hub-grid">${issueCards.join('')}</div>`) + section('The publishing rhythm', `<div class="hub-two"><p>One substantial feature anchors each monthly issue. The Daily Desk and Agentic@Enigmas hold shorter dispatches between covers. Future covers are chosen after the work is ready.</p><ul class="hub-list"><li><strong>Next issue:</strong> In preparation. No publication date has been announced.</li><li><a href="/daily-desk">Visit the Daily Desk ↗</a></li><li><a href="/subscribe">Get issue updates ↗</a></li></ul></div>`)),
    '/culture': shell('Culture.', 'Music, technology, art, and the stories that make a world feel lived in.', section('After hours', `<div class="hub-grid">${card('/ether','/media/ether-1.jpg','Listening room','The Ether Room','An illustrated passage through cosmic funk.')}${card('/tech-lounge','/media/tech-lounge.jpg','Technology culture','Tech@Lounge','The machines, histories, and questions around us.')}${card('/about/diana','/media/diana.jpg','Portrait','For Diana','A personal tribute through a mythic name.')}</div>`) + section('Continue reading', `<p>Culture is a way into the larger conversation. Follow the questions from <a href="/culture">the rooms</a> into <a href="/inquiry">Inquiry</a>, or return to <a href="/issues">the current issue</a>.</p>`)),
    '/food': shell('Food.', 'A magazine table for pleasure, craft, science, and the people who make a meal memorable.', `<div class="hub-banner"><img src="/media/food.jpg" alt="Original editorial illustration of a warmly lit shared table with food and drinks"><div><span class="hub-meta">The food desk / Opening edition</span><h2>A table is a world.</h2><p>Every plate has a history. Every good recipe begins with attention.</p><a href="#food-departments">Explore the departments ↓</a></div></div>` + section('At the table', `<p>Food enters Infinity as a new editorial desk. Its six departments are open for ideas; reported reviews, tested recipes, and health claims will carry their own sources and methods when published.</p>`) + `<section class="hub-section" id="food-departments"><h2>Explore Food.</h2>${departments(foodDepartments)}</section>`),
    '/music': shell('Music.', 'Ethereal listening, deep grooves, and the minds that make sound feel like another place.', `<div class="hub-banner"><img src="/media/ether-1.jpg" alt="Original illustrated cosmic music scene"><div><span class="hub-meta">The listening desk / Opening edition</span><h2>Follow the frequency.</h2><p>Scroll through image, rhythm, and atmosphere in the Ether Room.</p><a href="/ether">Enter the Ether Room ↗</a></div></div>` + section('The listening room', `<div class="hub-grid">${card('/ether','/media/ether-2.jpg','Visual mixtape','The Ether Room','Four illustrated scenes and a linked cosmic funk mix. Playback begins only when you choose it.')}${card('/culture','/media/ether-3.jpg','Beyond the track','Culture','Art and stories surrounding the music.')}</div>`) + section('Music departments', departments(musicDepartments))),
    '/practice': shell('The Practice.', 'Movement, stillness, and the attention we bring to both.', section('FORM / A visual meditation', `<div class="hub-grid">${card('/form','/media/form-1.jpg','Seven movements','The art of the pause','A full screen study of posture, breath, composure, and energy.')}</div><p class="hub-small">The portraits are interpretive illustrations. Captions describe the intention of each scene, not instruction for combat or medical care.</p>`) + section('The body as a question', `<div class="hub-two"><p>Where does a movement begin? What changes when we slow down enough to notice it? The Practice will study form, recovery, discipline, and attention through images and careful writing.</p><p>Start with <a href="/form">FORM</a>. The sequence is navigable by arrows, touch, or keyboard, and sound is optional.</p></div>`) + section('The Practice departments', departments(practiceDepartments))),
    '/inquiry': shell('Academic Journal.', 'Research, journals, learning paths, and the questions that refuse an easy answer.', section('Choose a door', `<div class="hub-grid">${card('/journal','/media/research.jpg','Method and evidence','Research Journal','Working notes with their methods and limits.')}${card('/learning','/media/learning.jpg','Guided study','Learning Center','A path into systems, AI, law, and technical practice.')}${card('/enigmas','/media/enigmas-politics.jpg','Essays and argument','Agentic@Enigmas','Longer ideas tested in public.')}</div>`) + section('A standard of proof', `<p>Each piece should tell you what is observed, what is inferred, and what remains to be checked. Read <a href="/about/standards">the editorial standards</a> before following the trail.</p>`) + section('The journal departments', departments(journalDepartments))),
    '/daily-desk': shell('The Daily Desk.', 'A small, changing desk of technology signals from their original publisher and original notes from Infinity.', section('Outside signals', `<p>These headlines come from the GitHub Changelog feed. They link to GitHub and may change as that feed updates. They are not Infinity reporting.</p><div class="hub-results" id="signal-grid" aria-live="polite"><a class="hub-result" href="/tech-lounge"><span>From Infinity / Technology culture</span><h2>Tech@Lounge</h2><p>Begin with the original reading room while the feed loads.</p></a></div><p id="signal-status" class="hub-small">Loading outside updates…</p>`) + section('Original desks', `<div class="hub-grid">${card('/blog','/media/tech-macro.jpg','Opinion & ideas','Agentic@Enigmas','Editorial notes and questions between larger features.')}${card('/enigmas','/media/enigmas-politics.jpg','Essays','The Reading Room','Original analysis and argument.')}${card('/issues','/media/cover.jpg','The magazine','Current issue','A deliberate selection from across the house.')}</div>`) + section('The Daily Desk departments', departments(deskDepartments))),
    '/blog': shell('Agentic@Enigmas.', 'Opinion and ideas from the Daily Desk: short notes from the Enterprise between the longer essays and research files.', section('Opinion & ideas / September 2026', `<div class="hub-two"><article id="stage-labels"><p class="hub-meta">Editorial note / 26 September 2026</p><h2>Let a prototype be a prototype.</h2><p>A good idea earns attention before it earns certainty. We label a concept, a working prototype, and a validated result differently because each invites a different kind of trust. That distinction gives a reader room to be curious without mistaking a proposal for a finished institution.</p><p><a href="/development/atlas">Inspect the project stages ↗</a></p></article><article id="image-record"><p class="hub-meta">Editorial note / 26 September 2026</p><h2>What an image can say.</h2><p>An illustration can make a future visible. It cannot prove that the pictured building exists, that the product works, or that a journey has been taken. The caption is where imagination meets the record.</p><p><a href="/about/standards">Read the editorial standard ↗</a></p></article></div>`) + section('Continue through the Desk', `<p>A brief note can open a question. The <a href="/journal">Research Journal</a> follows the method; <a href="/enigmas">Agentic@Enigmas</a> carries the longer essays.</p>`) + section('Opinion & ideas departments', departments(opinionDepartments))),
    '/search': shell('Find a thread.', 'Search the original essays, public projects, and rooms of Infinity Enterprises.', `<section class="hub-section"><label for="site-query" class="hub-meta">Search the publication</label><div class="hub-search"><input id="site-query" type="search" autocomplete="off" placeholder="Try AI governance, music, research…" aria-describedby="search-count"></div><p id="search-count" class="hub-result-count" aria-live="polite"></p><div id="search-results" class="hub-results"></div></section>`),
    '/reading-list': shell('Your reading list.', 'Stories you save stay in this browser on this device.', section('Saved for later', `<div id="saved-reading-list" class="hub-results"></div><p class="hub-small">This list is stored locally in your browser. Clearing browser storage removes it.</p>`)),
    '/subscribe': shell('The monthly letter.', 'A note from the magazine when a new issue is ready, with occasional short dispatches.', section('Join the issue list', `<p>The email edition is being prepared. Leave your address to receive a launch notice and future issue updates. No message will be sent until delivery is configured.</p><form class="hub-form" action="/api/subscribe" method="post"><label for="subscriber-email">Email address</label><input id="subscriber-email" type="email" name="email" autocomplete="email" required maxlength="254"><label class="check"><input type="checkbox" name="consent" value="yes" required><span>I agree to receive Infinity Enterprises issue updates by email. I can unsubscribe at any time.</span></label><label class="trap" aria-hidden="true">Leave this blank<input name="website" tabindex="-1" autocomplete="off"></label><button type="submit" class="hub-button">Join the list ↗</button><small>We keep your address only for the issue list. <a href="/privacy">Privacy details</a>.</small></form><p><a href="/feed.xml">Use an RSS reader instead ↗</a></p>`) + section('From the current issue', `<div class="hub-grid">${issueCards.slice(0,3).join('')}</div>`)),
    '/contact': shell('Contact the Enterprise.', 'Corrections, project inquiries, and thoughtful partnerships begin here.', section('Send a note', `<form class="hub-form" action="/api/contact" method="post"><label for="contact-name">Name</label><input id="contact-name" name="name" required maxlength="100" autocomplete="name"><label for="contact-email">Email address</label><input id="contact-email" name="email" type="email" required maxlength="254" autocomplete="email"><label for="contact-topic">Topic</label><select id="contact-topic" name="topic"><option>Editorial correction</option><option>Project inquiry</option><option>Partnership</option><option>General note</option></select><label for="contact-message">Message</label><textarea id="contact-message" name="message" required minlength="10" maxlength="3000"></textarea><label class="trap" aria-hidden="true">Leave this blank<input name="website" tabindex="-1" autocomplete="off"></label><button type="submit" class="hub-button">Send the note ↗</button><small>Your details are used to review and respond to this message. <a href="/privacy">Privacy details</a>.</small></form>`) + section('A correction belongs in the record', `<p>When a published claim changes, the affected page should be updated. See <a href="/about/standards">the editorial standards</a> for the distinction between a correction and an evolving working note.</p>`)),
    '/partners': shell('Partner with Infinity.', 'A selective invitation to support original editorial work without taking control of it.', section('The available settings', `<div class="hub-grid">${card('/issues','/media/cover.jpg','Issue partnership','The monthly edition','A clearly identified placement at the issue level.')}${card('/culture','/media/ether-1.jpg','Culture partnership','A room of its own','A marked sponsorship beside a relevant culture feature.')}${card('/inquiry','/media/research.jpg','Research partnership','Support the questions','Support an independent desk without shaping its conclusions.')}</div>`) + section('Editorial boundary', `<div class="hub-note"><p>Sponsorships will be plainly labeled. Partners will not choose findings, edit independent analysis, or turn a concept into a claim of completed work. Audience figures and prices are available only after measurement and a specific proposal.</p></div><a class="hub-link" href="/contact">Start a partnership conversation ↗</a>`)),
    '/support': shell('Support the work.', 'Help the publication grow while keeping the stories open to read.', section('What we are preparing', `<div class="hub-grid">${card('/issues','/media/cover.jpg','Collector edition','Volume 01','A considered digital collection of the first issue, in preparation.')}${card('/culture','/media/ether-2.jpg','Art edition','The illustrated rooms','Selected original artwork, subject to final rights review.')}${card('/subscribe','/media/research.jpg','Readers first','The monthly letter','Issue notes and a first look at what is next.')}</div><div class="hub-note"><p>Purchases and paid memberships are not active yet. Any future paid edition would be offered only after a separate eligible service, rights review, and clear terms are in place.</p></div><a class="hub-link" href="/subscribe">Get notified when editions are ready ↗</a>`)),
    '/privacy': shell('Privacy and advertising.', 'A plain description of what this publication currently collects and what changes when new services are added.', section('Current site behavior', `<ul class="hub-list"><li>Public pages do not require an account. The opening remembers whether you have seen it for this browser session.</li><li>Saved stories are kept in your browser on this device. We do not receive that reading list.</li><li>The staff area uses a secure session cookie after authorized sign in.</li><li>Contact messages and issue list addresses are stored for their stated purposes. A subscription can be removed using the unsubscribe link when delivery begins or by contacting the publication.</li><li>The Daily Desk requests public headlines from GitHub's changelog feed through the site server. The Ether Room opens a YouTube player only after you press Play; YouTube may then receive information according to its own terms.</li><li>This publication does not add a third party analytics script or store a visitor browsing log in its database. The hosting service processes operational traffic and logs under its own terms.</li></ul>`) + section('Advertising status', `<p>Google advertising and paid checkout are not active. If we add advertising, we will update this page with the relevant vendors, cookie disclosures, and consent controls before serving ads. <a href="/contact">Ask a privacy question ↗</a></p>`)),
  };
  const searchRecords = [
    ...stories.map(s=>({title:s.title,description:s.dek,category:s.section,url:'/enigmas/'+s.slug})),
    ...projects.map(p=>({title:p.title,description:p.description,category:'Project / '+p.stage,url:'/development/atlas'})),
    ...[['The Daily Desk','News and technology signals','/daily-desk'],['Culture','Music, technology and art','/culture'],['Food','Taste, craft and food science','/food'],['Music','Artist profiles and the Ether Room','/music'],['MOTOR','Cars and visual design','/motor'],['The Practice','Movement and meditation','/practice'],['Academic Journal','Research and journals','/inquiry'],['Agentic@Enigmas','Daily Desk opinion and ideas','/blog'],['In Development','AI systems and product concepts','/development'],['About the Enterprise','Purpose and editorial standards','/about'],['The Ether Room','Cosmic funk listening room','/ether'],['FORM','Martial arts as form and energy','/form'],['Tech@Lounge','Technology culture','/tech-lounge'],['Learning Center','Guided roadmaps','/learning'],['Research Journal','Methods and questions','/journal']].map(([title,description,url])=>({title,description,category:'Room',url})),
  ];
  const existingDepartments = {
    '/motor': '<section class="embedded-departments" id="motor-departments"><div class="embedded-departments-inner"><span class="hub-meta">MOTOR / The editorial desks</span><h2>Beyond the gallery.</h2><p>The current visual edition is an original illustration series. These departments will host reported pieces as they are made.</p>' + departments(motorDepartments) + '</div></section>',
    '/journal': '<section class="embedded-departments" id="journal-departments"><div class="embedded-departments-inner"><span class="hub-meta">Academic Journal / The departments</span><h2>Ways into the work.</h2><p>Working notes remain labeled as such. Follow the methods, cases, and questions from here.</p>' + departments(journalDepartments) + '</div></section>',
    '/tech-lounge': '<section class="embedded-departments" id="tech-departments"><div class="embedded-departments-inner"><span class="hub-meta">Tech Lounge / The departments</span><h2>Open the workshop.</h2><p>Technology as object, system, culture, and possibility.</p>' + departments(techDepartments) + '</div></section>'
  };
  return {pages,searchRecords,existingDepartments};
}
